# O Problema
Sliding Puzzle - Bloco Deslizante

In [3]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

In [61]:
#Imports
import numpy as np
import itertools
import copy
import resource
import sys

In [62]:
resource.setrlimit(resource.RLIMIT_STACK, (2**40,-1))
sys.setrecursionlimit(10**9)

In [63]:
target = np.array([[1,2,3], [4,5,6], [7,8,0]])
target_abs = "123456780"
mvs = [(0, -1), (0, 1), (-1, 0), (1, 0)]


In [64]:
class Board():
  def __init__ (self, state, parent): 
    self.state = state
    self.abstraction = self.get_abstraction()
    self.shape = state.shape
    self.empty_pos = self.get_empty_pos()
    self.parent = parent
    self.children = []
 

  def get_abstraction(self):
    aux = np.array2string(self.state.flatten(), separator='')
    aux = aux.replace('[', '')
    aux = aux.replace(']', '')
    return aux


  def get_empty_pos(self):
    a, b = np.where(self.state == 0)
    a = a.item()
    b = b.item()
    return (a, b)


  def set_children(self):
    childs = []
    moves = self.get_avaiable_moves(mvs)

    for move in moves:
      new_state = self.apply_move(move)
      child = Board(new_state, self)
      childs.append(child)
    
    self.children = childs


  def get_avaiable_moves(self, moves):
    x, y = self.empty_pos
    move_list = []

    for i_x, i_y in moves:
      aux_x = x + i_x
      aux_y = y + i_y
      if((-1 < aux_x < self.shape[0]) and (-1 < aux_y < self.shape[1])):
        move_list.append((aux_x, aux_y)) 

    return move_list


  def apply_move(self, move):
    next_state = copy.deepcopy(self.state)
    next_state[self.empty_pos], next_state[move] = next_state[move], next_state[self.empty_pos]
    return next_state


In [158]:
def print_solution (start, end): 
  solution = []
  while end.parent != None: 
    solution.append(end.state)
    end = end.parent 
  
  solution = solution[::-1]

  print(start.state)
  print("")

  for state in solution:
    print(state)
    print("")

## Busca em largura

In [90]:
def breadth_search(state):
  visited = set()

  if state.abstraction == target_abs:
    return state
  
  aux = []
  aux.append(state)
  visited.add(state)
  while(len(aux) > 0):
    aux[0].set_children()
    
    for i in aux[0].children:
      if i in visited:
        continue
      visited.add(i)
      if i.abstraction == target_abs:
        return i
      aux.append(i)
    aux.pop(0)  

In [155]:
board =np.array([[1, 2, 3],
                 [5, 6, 8],
                 [4, 0, 7]])

In [156]:
a = Board(board, None)
b = breadth_search(a)

In [157]:
print_solution(a, b)

[[1 2 3]
 [5 6 8]
 [4 0 7]]

[[1 2 3]
 [5 6 8]
 [4 7 0]]

[[1 2 3]
 [5 6 0]
 [4 7 8]]

[[1 2 3]
 [5 0 6]
 [4 7 8]]

[[1 2 3]
 [0 5 6]
 [4 7 8]]

[[1 2 3]
 [4 5 6]
 [0 7 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]



## Busca em Profundidade

In [101]:
def depth_search(state):
  
  visited = set()
  return dsr(state, visited)

def dsr(state, visited):  

  if state.abstraction == target_abs:
    return state

  visited.add(state.abstraction)
  state.set_children()
  
  for item in state.children:
      if item.abstraction in visited:
        del item
        continue
      solution = dsr(item, visited)
      if solution is not None:
        return solution

In [151]:
board =np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 0, 8]])

In [152]:
a = Board(board, None)
b = depth_search(a)

In [154]:
print_solution(a, b) 

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [0 7 8]]

[[1 2 3]
 [0 5 6]
 [4 7 8]]

[[1 2 3]
 [5 0 6]
 [4 7 8]]

[[1 2 3]
 [5 6 0]
 [4 7 8]]

[[1 2 0]
 [5 6 3]
 [4 7 8]]

[[1 0 2]
 [5 6 3]
 [4 7 8]]

[[0 1 2]
 [5 6 3]
 [4 7 8]]

[[5 1 2]
 [0 6 3]
 [4 7 8]]

[[5 1 2]
 [6 0 3]
 [4 7 8]]

[[5 1 2]
 [6 3 0]
 [4 7 8]]

[[5 1 0]
 [6 3 2]
 [4 7 8]]

[[5 0 1]
 [6 3 2]
 [4 7 8]]

[[0 5 1]
 [6 3 2]
 [4 7 8]]

[[6 5 1]
 [0 3 2]
 [4 7 8]]

[[6 5 1]
 [3 0 2]
 [4 7 8]]

[[6 5 1]
 [3 2 0]
 [4 7 8]]

[[6 5 0]
 [3 2 1]
 [4 7 8]]

[[6 0 5]
 [3 2 1]
 [4 7 8]]

[[0 6 5]
 [3 2 1]
 [4 7 8]]

[[3 6 5]
 [0 2 1]
 [4 7 8]]

[[3 6 5]
 [2 0 1]
 [4 7 8]]

[[3 6 5]
 [2 1 0]
 [4 7 8]]

[[3 6 0]
 [2 1 5]
 [4 7 8]]

[[3 0 6]
 [2 1 5]
 [4 7 8]]

[[0 3 6]
 [2 1 5]
 [4 7 8]]

[[2 3 6]
 [0 1 5]
 [4 7 8]]

[[2 3 6]
 [1 0 5]
 [4 7 8]]

[[2 3 6]
 [1 5 0]
 [4 7 8]]

[[2 3 0]
 [1 5 6]
 [4 7 8]]

[[2 0 3]
 [1 5 6]
 [4 7 8]]

[[2 5 3]
 [1 0 6]
 [4 7 8]]

[[2 5 3]
 [0 1 6]
 [4 7 8]]

[[0 5 3]
 [2 1 6]
 [4 7 8]]

[[5 0 3]
 [2 1

## Discorra sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
  
  O Algoritmo de Busca em Largura utiliza muito mais memória que a Busca em profundidade, em decorrencia de ter que armazenar vários estados ao mesmo tempo. Em casos mais complexos a Busca em Largura pode até estourar a memória disponível.

2.   Processamento

  Dependendo do tabuleiro utilizado o tempo de processamento em ambos fica grande. Para alguns casos a Busca em profundidade não retornou uma solução, enquanto que a busca em largura demora para achá-los.
